# Generated by Django 2.2.8 on 2019-12-27 12:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191227_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
